Repository tired-of-cancer/eslint-config-toc, pull requests merged in 2022-08, with the labels that each got.

#23 Added nextjs config
  README.md
  nextjs.js
  package.json
  react-native.js
  yarn.lock
Labels: feature

#24 NextJS Typo
  package.json
Labels: bug

#25 Add toc bot pat token and linting step to workflow
  .github/workflows/draft-release-notes.yml
  README.md
Labels: feature, skip-changelog

#26 Install linting dependencies on release note flow
  .github/workflows/draft-release-notes.yml
Labels: bug, skip-changelog

#27 Fix release flow configuration
  .github/workflows/draft-release-notes.yml
Labels: bug, skip-changelog

#28 Disallow use of semicolon
  .eslintrc.js
  .prettierrc.js
  README.md
  nextjs.js
  react-native.js
  react.js
  setup-plugins.js
  typescript.js
Labels: feature

#30 Disable conflicting unicorn loop rule
  typescript.js
Labels: bug

#31 Fix linting workflow false negative
  .github/workflows/linting.yml
Labels: bug

#32 moved filename case to typescript
  .gitignore
  react.js
  typescript.js
Labels: feature

#33 reverted filename case
  react.js
  typescript.js
Labels: feature

#34 Add nextjs typescript base config file
  README.md
  package.json
  tsconfig-nextjs.json
  yarn.lock
Labels: feature
